# Typical settings used - just for reproduction

compute_query_id = 'on'
fsync = off
checkpoint_timeout = 86399

# Performance & Planning
from_collapse_limit = 20
join_collapse_limit = 20
default_statistics_target = 2500

max_parallel_workers_per_gather = 4
max_worker_processes = 8
max_parallel_workers = 8

parallel_setup_cost = 0.01
parallel_tuple_cost = 0.00001
min_parallel_table_scan_size = 0
min_parallel_index_scan_size = 0

shared_buffers='1GB'
work_mem='64MB'

# This should never happen with basic configuration.
# But it may happen with FDW or other custom storage.
# So, this time is enough to identify if something goes wrong.
statement_timeout = '20min'